import { Fragment, SetStateAction, useEffect, useState } from 'react';
import Head from 'next/head';
import { GetStaticProps } from 'next';
import { SplashPage, SplashCollection } from '../typings';
import { fetchSplashPage } from '../utils/fetchSplashPage';
import { fetchSplashCollection } from '../utils/fetchSplashCollection';
import { urlFor } from '../sanity';
import Image from 'next/image';
import { PortableText } from '@portabletext/react';
import Mailer from '../components/Mailer';
import 'flowbite';

type Props = {
	splashPage: SplashPage;
	splashCollections: SplashCollection[];
};

const Home = ({ splashPage, splashCollections }: Props) => {
	return (
		<Fragment>
			<Head>
				<title>Maÿaz Collection</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			{/* Content */}
			<div className="flex-wrap mt-8 mb-12 lg:mt-40 lg:mb-40 bg-black">
				<Image
					src="/Logo_Full_Wht.svg"
					alt="MAŸAZ Collection logo"
					width={660}
					height={344}
					className="mx-auto pr-6"
				/>
				<div className="-mt-20">
					<h1 className="py-8 font-light text-center text-2xl uppercase tracking-[0.75em] -mt-12">
						<span className="block text-lg tracking-[0.5em] pb-2 text-mayaz">
							Our
						</span>
						<span className="ml-[0.75em] text-white">{splashPage.title}</span>
					</h1>
					<div className="grid grid-cols-1 md:grid-cols-2 gap-y-8 px-0 md:px-12 lg:px-0 xl:px-0 md:gap-x-0 lg:flex lg:gap-6 xl:gap-8 w-full max-w-screen-xl mx-auto justify-center py-8">
						{splashCollections.map((collection) => (
							<div
								key={collection._id}
								className="relative h-full mx-auto overflow-hidden"
							>
								<Image
									src={urlFor(collection?.thumbnail).url()}
									alt="Her Virtue Collection"
									width={297}
									height={423}
									style={{
										objectFit: 'cover',
									}}
								/>
								<div className="absolute inset-8 lg:inset-4 xl:inset-6 h-auto flex items-end justify-center">
									<button
										data-modal-target={collection._id}
										data-modal-toggle={collection._id}
										className="cursor-pointer bg-opacity-50 bg-black w-full text-center py-6 border border-white"
										type="button"
									>
										<h2 className="font-light text-lg uppercase tracking-[0.75em]">
											<span className="block text-xs tracking-[0.5em] pb-2 text-mayaz">
												Her
											</span>
											<span className="ml-[0.75em] text-white">
												{/* The button to open modal */}
												{collection.buttonLabel}
											</span>
										</h2>
									</button>
								</div>
								{/* Main modal */}
								<div
									id={collection._id}
									aria-hidden="true"
									className="modalEl fixed top-0 left-0 right-0 z-50 hidden w-full p-8 lg:p-4 overflow-x-hidden overflow-y-auto inset-0 md:inset-0 h-modal md:h-full bg-mayaz bg-opacity-70 backdrop-blur-sm"
								>
									<div className="relative w-[930px] h-full md:h-auto">
										{/* Modal content */}
										<div className="relative bg-black rounded-none p-0 shadow-lg shadow-black/20">
											<Image
												src={urlFor(collection?.modalImage).url()}
												alt="Her Virtue"
												width={930}
												height={626}
												style={{
													objectFit: 'cover',
												}}
												className="h-full w-full object-cover"
											/>
											{/* Content container */}
											<div className="md:absolute top-0 w-full">
												{/* Modal header */}
												<div className="flex items-start justify-between p-3 lg:p-4 lg:space-y-2">
													<button
														type="button"
														className="text-mayaz bg-transparent hover:text-white text-lg p-1.5 ml-auto inline-flex items-center"
														data-modal-hide={collection._id}
													>
														X<span className="sr-only">Close modal</span>
													</button>
												</div>
												{/* Modal body */}
												<div className="p-6 space-y-6 lg:space-y-8">
													<h2 className="text-4xl text-center font-light text-white uppercase tracking-[0.75em]">
														{collection.modalHeader}
													</h2>
													<div>
														<Image
															src="/temp/Splash/quote-marks.svg"
															alt="Her Virtue Collection"
															width={50}
															height={45}
															style={{
																objectFit: 'contain',
															}}
															className="mx-auto"
														/>
													</div>
													<div className="modalbody text-xl md:px-8 lg:px-16 text-center leading-relaxed text-white">
														<PortableText value={collection.modalBody} />
													</div>
													<p className="text-base text-center leading-relaxed text-mayaz">
														{collection.modalSource}
													</p>
												</div>
												{/* Modal footer */}
												<div className="flex items-center p-6 space-y-2" />
											</div>
											{/* End content container */}
										</div>
									</div>
								</div>
								{/* End modal */}
							</div>
						))}
					</div>
					<div className="hidden lg:block">
						<p className="uppercase font-light text-lg text-center text-mayaz tracking-[0.5em] ml-[0.75em] py-8">
							<span className="pr-[0.5em]">[</span>
							{splashPage.launchField1}{' '}
							<span className="text-white">February 25, 2023</span> -{' '}
							{splashPage.launchField2}
							<span className="pl-[0.5em]">]</span>
						</p>
					</div>
					<div className="lg:hidden mb-4">
						<p className="uppercase font-light leading-8 text-lg text-center text-mayaz tracking-[0.5em] ml-[0.75em] py-8">
							<span className="pr-[0.5em]">[</span>
							{splashPage.launchField1}
							<span className="pl-[0.5em]">]</span>
							<br />
							<span className="text-white">February 25, 2023</span>
							<br />
							<span className="pr-[0.5em]">[</span>
							{splashPage.launchField2}
							<span className="pl-[0.5em]">]</span>
						</p>
					</div>
				</div>
				<div className="w-full item-self-center">
					<Mailer />
				</div>
			</div>
			{/* End content */}
		</Fragment>
	);
};
export default Home;

export const getStaticProps: GetStaticProps<Props> = async () => {
	const splashPage: SplashPage = await fetchSplashPage();
	const splashCollections: SplashCollection[] = await fetchSplashCollection();

	return {
		props: {
			splashPage,
			splashCollections,
		},
		revalidate: 60,
	};
};
